
stages:
  - build
  - test

react-build:
  image: node:latest
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  cache:
    paths:
    - node_modules/

react-test:
  image: node:latest
  stage: test
  script: npm test

python-build:
  image: gpdowning/python
  stage: build
  script: pip install -r backend/requirements.txt

python-test:
  image: gpdowning/python
  stage: test
  script: pip install -r backend/requirements.txt & python backend/test.py


