image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - apt update
    - apt install python3-pip
    - Y
    - pip3 install requests
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test

backend_testing:
  script:
    - pip3 --version
    - python3 backend/test.py
